# Generated by Django 3.2.4 on 2022-01-15 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'учебная сессия',
                'verbose_name_plural': 'Учебные сессии',
                'db_table': 'educational_sessions',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TrainingStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('А', 'A'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1, verbose_name='Буква')),
                ('number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Цифра')),
            ],
            options={
                'verbose_name': 'поток',
                'verbose_name_plural': 'Потоки',
                'db_table': 'training_streams',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.trainingstream', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'Ученики',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], verbose_name='Оценка')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствие')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.educationalsession', verbose_name='')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'Оценки',
                'db_table': 'scores',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.TextField(verbose_name='Домашнее задание')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'домашнее задание',
                'verbose_name_plural': 'Домашнее задания',
                'db_table': 'homework',
            },
        ),
        migrations.AddField(
            model_name='educationalsession',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.homework', verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='educationalsession',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='educationalsession',
            name='training_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.trainingstream', verbose_name='Поток'),
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('training_stream_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Цифра потока')),
                ('available_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.educationalmaterial', verbose_name='Доступно после прохождения материала номер')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'учебный материал',
                'verbose_name_plural': 'Учебные материалы',
                'db_table': 'educational_materials',
            },
        ),
    ]
