# Generated by Django 3.2.4 on 2021-08-22 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Добавление')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'Ученики',
                'db_table': 'pupils',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('score', models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], verbose_name='Оценка')),
                ('is_present', models.BooleanField(default=False, verbose_name='Присутствие')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('pupil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.pupil', verbose_name='Ученик')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'запись в дневнике',
                'verbose_name_plural': 'Записи в дневнике',
                'db_table': 'diaries',
            },
        ),
    ]
