# Generated by Django 3.2.4 on 2021-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Решено?')),
                ('expected_time', models.DateTimeField(verbose_name='Ожидаемое время решения')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
