# Generated by Django 3.2.4 on 2021-08-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210731_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={'verbose_name': 'тип задачи', 'verbose_name_plural': 'Типы задачи'},
        ),
    ]
