# Generated by Django 3.2.4 on 2022-01-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
